name: "Deploy Express application to FC"
triggers:
  github:
    secret: test
    events:
      - eventName: "push"
        filter: 'body.ref in ["refs/heads/master"]'
steps:

#  - run: npm i
  # working-directory: ./code
  - run: npm i @serverless-devs/s -g --registry=https://registry.npmmirror.com
  - run: s -v
  - run: echo ${{secrets.SIMPLE_ALIYUN_ACCOUNTID}}
  - run: echo ${{secrets.SIMPLE_ALIYUN_AK}}
  - run: echo ${{secrets.SIMPLE_ALIYUN_SK}}
  - run: s config add --AccountID ${{secrets.SIMPLE_ALIYUN_ACCOUNTID}}  --AccessKeyID ${{secrets.SIMPLE_ALIYUN_AK}}  --AccessKeySecret ${{secrets.SIMPLE_ALIYUN_SK}} -a default -f
  - run: s deploy --use-local -y
